### ISSUE TITLE
GET_SAVE_ADD_PATH error

### ISSUE THREAD

**Issue by fenniro** [dawhite/VCTK#7]
Hi Devin,
We are working at home with temporary ENVI 5.5/IDL 8.7 licenses.  We have been using the VCTK at work just fine since 2013.  I installed the latest VCTK to the ENVI Classic save_add directory and everything went fine until I tried to open a VIIRS .h5 file.  I got this error:
% Variable is undefined: <No name>.
% Execution halted at: GET_SAVE_ADD_PATH   11 
%                      VIIRS_DATA_QUERY  169 
%                      VCTK_EVENT         90 
%                      WIDGET_PROCESS_EVENTS
%                      $MAIN$          
We tried the obvious things like moving the save_add directory out of the installation path, and editing the envi.cfg file to reflect this change.  What do you suppose might be wrong?  Thanks, -Rob.

**Comment by dawhite** [comment]
One of your colleagues reached out to me via email with a similar error message. I've never seen that one before. It's being generated by a very simple function I wrote that checks which version of ENVI is running so it can find the save_add directory. If you have access to ENVI+IDL, make sure both are running and then enter this at the IDL command line:

e = envi(/current)
test = obj_valid(e)
print, test

and let me know what comes back. The first line is what seems to be throwing the error, which is weird. Granted, I'm running ENVI 5.2 and use that to build VCTK, so maybe Harris changed the API and that has broken all of my plugins...because I use that function with all of them...but until recently that function was completely benign.

**Comment by fenniro** [comment]
Devin,

Here is what I got running those commands, after running the VCTK and getting the error on attempting to open a .h5 file.  The first command gives me the same error that the VCTK gave:

ENVI> e=envi(/current)
% Variable is undefined: <No name>.
% Execution halted at: GET_SAVE_ADD_PATH   11
%                      VIIRS_DATA_QUERY  169
%                      VCTK_EVENT         90
%                      WIDGET_PROCESS_EVENTS
%                      $MAIN$
ENVI> test=obj_valid(e)
ENVI> print, test
   0
ENVI>

**Comment by dawhite** [comment]
Fixed with v1.1.9, which is now available on the Releases page. Turns out that ENVI 5.5.3 has a bug in it that broke one of my support programs (GET_SAVE_ADD_PATH). According to Harris, a fix for the bug will be included in the next release of ENVI. What I implemented is a workaround that suppresses the error message and allows the plugin to continue running.
